import "./globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen flex  justify-center">
          <div className="max-w-md w-full  border-2 shadow-xl border-gray-400">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
